gin:
    address: http://gintestserver
    port: 3000
git:
    address: gintestserver
    port: 22
    hostkey: "gintestserver,172.18.0.2 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG0pI0YT4rNV3vP8TA0owc2aEhaWyT/oxXTdZXNtEOavvgBHRyD/SPGohRelWwvSTHood0e/PTH2K6R0/Ef9cxw="

annex:
    minsize: 50kB
    exclude: ["*.foo", "*.md", "*.py"]
