sudo: required

services:
    - docker

before_install:
    - docker pull gnode/ginhome
    - ./start-server.sh
    - docker ps -a

script:
    - ./run-tests-in-container.sh
    - cat log/gin/gin.log
