sudo: required

services:
    - docker

env:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_install:
    - docker pull gnode/ginhome
    - ./start-server.sh

script:
    - cd $TRAVIS_BUILD_DIR
    - curl localhost:3000
    - ./test-git-annex-selection.sh
