sudo: false

services:
    - docker

env:
    - PATH=$PATH:$TRAVIS_BUILD_DIR/bin

before_install:
    - docker pull gnode/ginhome

script:
    - cd $TRAVIS_BUILD_DIR
    - ./start-server.sh
    - docker ps
    - curl 127.0.0.1:3000
    - ./test-git-annex-selection.sh
