sudo: required

services:
    - docker

before_install:
    - docker pull gnode/ginhome
    - ./start-server.sh
    - docker ps -a
    - while ! curl localhost:3000; do sleep 1; done

script:
    - ./run-all-tests.sh
