sudo: required

services:
    - docker

before_install:
    - wget https://web.gin.g-node.org/achilleas/gin-cli-builds/raw/master/gin-cli-latest.deb
    - sudo dpkg -i gin-cli-latest.deb
    - docker pull gnode/ginhome
    - ./start-server.sh
    - docker ps -a
    - while ! curl localhost:3000 -so /dev/null; do sleep 1; done

script:
    - ./run-all-tests.sh

after_script:
    - cat ./log/gin/gin.log
