sudo: required

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install git-annex
    - docker pull gnode/ginhome
    - ./start-server.sh
    - docker ps -a
    - while ! curl localhost:3000 -so /dev/null; do sleep 1; done

script:
    - ./run-all-tests.sh
    - cat ./log/gin/gin.log
