sudo: false

services:
    - docker

before_install:
    - docker pull gnode/ginhome

script:
    - cd $TRAVIS_BUILD_DIR
    - ./start-server.sh
    - docker ps
    - ./run-tests-in-container.sh
    - cat log/gin/gin.log
