sudo: required

services:
    - docker

before_install:
    - sudo apt-get update
    - sudo apt-get install git-annex
    - docker pull gnode/ginhome
    - ./start-server.sh
    - docker ps -a
    - while ! curl localhost:3000 -so /dev/null; do sleep 1; done

script:
    - mkdir foobar
    - cd foobar
    - git init
    - git config --local user.name "foo"
    - git config --local user.email "foo@bar.com"
    - git status
    - git commit --allow-empty -m "Initial commit"
    - git-annex init testuser@1ea51e4841c3 -c annex.ssh-options="-o StrictHostKeyChecking=no -i /root/tests/conf/gin/testuser.key"
    - ./run-all-tests.sh

after_script:
    - cat ./log/gin/gin.log
