#!/usr/bin/env bash
#
# Use this script to start the test runner container in the background and execute any command that is supplied as an argument.
# The container is killed at the end of the run.
# The script blindly passes whatever arguments are supplied to the container as a command, so proper command syntax and paths are required.
# Env variables are set to use the tester config and log directories for gin-cli.

cmd=$*

set -euo pipefail

loc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
pushd $loc
source ${loc}/scripts/setenv.sh

mounts="
-v ${GIN_CONFIG_DIR}:/home/ginuser/conf:ro
-v ${GIN_LOG_DIR}:/home/ginuser/log
-v ${loc}/scripts/:/home/ginuser/scripts:ro
-v ${loc}/bin/:/ginbin:ro
"
env="--env-file=${loc}/scripts/contenv"

docker build --build-arg UID=${UID} -t ginclitestsmv dockerfiles/testerminver
docker run --rm --network=ginbridge ${mounts} ${env} -i --name gintestclientmv --entrypoint="/bin/bash" -d ginclitestsmv

# kill container on exit
trap 'docker kill gintestclientmv' EXIT

docker exec -i gintestclientmv $cmd
