#!/usr/bin/env bash

set -euo pipefail

loc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
pushd $loc

docker build --build-arg UID=${UID} -t ginclitestsmv dockerfiles/testerminver

source ${loc}/scripts/setenv.sh
mkdir -p ${GIN_LOG_DIR}
testlog=${GIN_LOG_DIR}/tests.log
echo "Running tests and logging to ${testlog}"
docker run --rm --network=ginbridge -v "${GIN_CONFIG_DIR}":/home/ginuser/conf -v "${GIN_LOG_DIR}":/home/ginuser/log -v "${loc}/scripts/":/home/ginuser/scripts -v "${loc}/bin/":/ginbin --env-file="${loc}/scripts/contenv" --name gintestclientmv ginclitestsmv 2>&1 | tee ${testlog}
