#!/usr/bin/env bash

set -euo pipefail

loc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
pushd $loc

docker build --build-arg UID=${UID} -t ginclitestsmv dockerfiles/testerminver

source ${loc}/scripts/setenv.sh
mkdir -p ${GIN_LOG_DIR}

mounts="
-v ${GIN_CONFIG_DIR}:/home/ginuser/conf:ro
-v ${GIN_LOG_DIR}:/home/ginuser/log
-v ${loc}/scripts/:/home/ginuser/scripts:ro
-v ${loc}/bin/:/ginbin:ro
"
env="--env-file=${loc}/scripts/contenv"
testlog=${GIN_LOG_DIR}/tests.log

echo "Running tests and logging to ${testlog}"
docker run --rm --network=ginbridge ${mounts} ${env} --name gintestclientmv ginclitestsmv 2>&1 | tee ${testlog}
