#!/usr/bin/env bash

loc=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
pushd $loc

docker exec gintestserver rm -rfv /data/ssh /data/gogs-repositories
docker exec gintestserverb rm -rfv /data/ssh /data/gogs-repositories
docker kill gintestserver gintestserverb
docker network rm ginbridge
