#!/usr/bin/env bash

if [[ $1 == "--update" ]]
then
    ncarg="--no-cache"
else
    ncarg=""
fi

set -euo pipefail
docker build ${ncarg} ginclibase -t gnode/gin-cli-deps
docker push gnode/gin-cli-deps
