auth:
    address: http://dev.g-node.org
    port: 10080
repo:
    address: http://dev.g-node.org
    port: 10080
git:
    address: dev.g-node.org
    port: 10022
annex:
    minsize: 1kb
    exclude: ["*.foo", "*.md", "*.py"]
